CU-a76awn_Check-site-accessibility_Fernanda-Kuhnen-Hermenegildo
saibrotech/site pull request #29
Opened 2021-08-30 13:36 UTC by fekuhnen

Changed members and portfolio accessibility.

2021-08-30 13:36 UTC, fekuhnen commented
Task linked: [CU-a76awn Check site accessibility](https://app.clickup.com/t/a76awn)

2021-08-30 21:21 UTC, gutivalente requested changes

2021-08-30 21:21 UTC, gutivalente commented on _includes/members.html
> +              aria-label="LinkedIn de {{ member.title }}"></i></a>
Esses `aria-label` vão ter que ser traduzidos

2021-09-01 11:49 UTC, gutivalente approved these changes

2021-09-01 11:50 UTC, merged