CU-6f2ffb_Add-Contact-section_Nicole-Buitoni
saibrotech/site pull request #7
Opened 2021-08-11 01:51 UTC by Nibuitoni

2021-08-11 11:58 UTC, gutivalente requested changes
![2021-08-11 08_56_28-SaibroTech](https://user-images.githubusercontent.com/78234245/129024761-a3c9ea30-71c0-481e-a0bc-26d253ef334b.png)

2021-08-11 12:53 UTC, gutivalente requested changes

2021-08-11 12:53 UTC, gutivalente commented on assets/css/creative.scss
> -
Eu não consegui descobrir o que são esses tracinhos, mas aparentemente sem eles esse arquivo quebra. ¯\_(ツ)_/¯
Deixa eles aí mesmo.

2021-08-11 23:21 UTC, Nibuitoni commented on assets/css/creative.scss
> -
adicionei os traços

2021-08-12 11:27 UTC, gutivalente approved these changes

2021-08-12 11:31 UTC, merged